### ISSUE TITLE
Could not resolve proxy : POST

### ISSUE THREAD

**Issue by jageshmaharjan** [MainRo/deepspeech-server#13]
It was working all fine until yesterday. 
All of sudden it didn't work from today.
I ran the curl command, 
`curl -x POST --data-binary @C23_597.wav http://localhost:8080/stt`
but i was issuing this error:
`curl: (5) Could not resolve proxy: POST`

**Comment by jageshmaharjan** [comment]
Figured out that it was parameter name (-x), it should be capital x (-X).

But now I am getting this error.
`curl: (52) Empty reply from server`

**Comment by MainRo** [comment]
Do you have any logs one the server side ?

**Comment by jageshmaharjan** [comment]
This is at the server side (with tensorflow-cpu):
```
(asr) jugs@docker:~/deepspeech-server$ deepspeech-server --config configzh.json creating model /home/jugs/deepspeech-server/zh_models/output_graph.pb /home/jugs/deepspeech-server/zh_models/alphabet.txt
2018-07-12 08:57:03.702111: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
```
This is at the server side (with tensorflow-gpu) [Another Azure Vm]:

```
(asr) maybe@maybe1:/data/jugs/asr/deepspeech-server$ deepspeech-server --config config_zh.json 
creating model /data/zh_data/exportDir/output_graph.pb /data/zh_data/alphabet.txt
TensorFlow: v1.6.0-16-gc346f2c
DeepSpeech: v0.2.0-alpha.5-0-g7cc8382
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-07-12 09:02:40.552685: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-12 09:02:40.898955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: Tesla M60 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: 7815:00:00.0
totalMemory: 7.94GiB freeMemory: 287.12MiB
2018-07-12 09:02:41.185586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 1 with properties: 
name: Tesla M60 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: 9062:00:00.0
totalMemory: 7.94GiB freeMemory: 287.12MiB
2018-07-12 09:02:41.499729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 2 with properties: 
name: Tesla M60 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: a7d4:00:00.0
totalMemory: 7.94GiB freeMemory: 287.12MiB
2018-07-12 09:02:41.783257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 3 with properties: 
name: Tesla M60 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: c057:00:00.0
totalMemory: 7.94GiB freeMemory: 287.12MiB
2018-07-12 09:02:41.783448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1227] Device peer to peer matrix
2018-07-12 09:02:41.783597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1233] DMA: 0 1 2 3 
2018-07-12 09:02:41.783622: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 0:   Y N N N 
2018-07-12 09:02:41.783644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 1:   N Y N N 
2018-07-12 09:02:41.783659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 2:   N N Y N 
2018-07-12 09:02:41.783672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 3:   N N N Y 
2018-07-12 09:02:41.783691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0, 1, 2, 3
2018-07-12 09:02:43.008518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 23 MB memory) -> physical GPU (device: 0, name: Tesla M60, pci bus id: 7815:00:00.0, compute capability: 5.2)
2018-07-12 09:02:43.010046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 23 MB memory) -> physical GPU (device: 1, name: Tesla M60, pci bus id: 9062:00:00.0, compute capability: 5.2)
2018-07-12 09:02:43.011394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 23 MB memory) -> physical GPU (device: 2, name: Tesla M60, pci bus id: a7d4:00:00.0, compute capability: 5.2)
2018-07-12 09:02:43.013102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 23 MB memory) -> physical GPU (device: 3, name: Tesla M60, pci bus id: c057:00:00.0, compute capability: 5.2)
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)

```

curl from remote [my machine]:
```
jugs@jugs:~$ curl -X POST --data-binary @Desktop/ForZhBig/dev/D8_997.wav http://13.66.16x.xx:8080/stt
curl: (52) Empty reply from server

```
EDIT::
By the way, with GPU it works.

```
jugs@jugs:~$ curl -X POST --data-binary @Desktop/ForZhBig/dev/D8_997.wav http://52.179.1x.xxx:8080/stt
fei1 zhou1 pu2 yu3 guo2 jia1 bao1 kuo4 an1 ge1 la1 mo4 sang1 bi3 ke4 ji3 nei4 ya4 bi3 shao4 fu4 de2 jiao3 sheng4 duo1 mei3 he2 pu3 lin2 xi1 bi3 wu3 guo2
```

**Comment by MainRo** [comment]
Are you sure that the cpu instance of the server is reachable ? On the server side you should have logs for each transcription, which is not the case here. Also the empty reply from curl may be due to a network issue such as a port not being mapped.

**Comment by jageshmaharjan** [comment]
The message is sporadic. Sometimes it works just out of the box, sometimes I get that message in the client. Not sure why it's like that. 
While DeepSpeech API works fine (`deepspeech alphabets.txt lm.binary trie file.wav`).

**Comment by MainRo** [comment]
ok, if you use curl in verbose mode, what is the output in case of error ? When the error occurs, is it systematic after the server started and no other request succeed, or does it happen sometimes on an instance that works ?

**Comment by jageshmaharjan** [comment]
Two things to note here,

while verbose mode on

```
jugs@jugs:~/Desktop/ForZhBig/fragments$ curl -X POST --data-binary @x1.wav http://docker:8080/stt -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 13.66.1xx.xx...
* TCP_NODELAY set
* Connected to docker (13.66.1xx.xx) port 8080 (#0)
> POST /stt HTTP/1.1
> Host: docker:8080
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 352044
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host docker left intact
curl: (52) Empty reply from server
```
And, I received the error on the server too, (without verbose too, don't know why it didn't appear earlier)

```
2018-07-16 08:54:13.718688: E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,750], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
2018-07-16 08:54:13.718748: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,750], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,750], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice)]]
Error running session: Invalid argument: NodeDef mentions attr 'identical_element_shapes' not in Op<name=TensorArrayV3; signature=size:int32 -> handle:resource, flow:float; attr=dtype:type; attr=element_shape:shape,default=<unknown>; attr=dynamic_size:bool,default=false; attr=clear_after_read:bool,default=true; attr=tensor_array_name:string,default=""; is_stateful=true>; NodeDef: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,750], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: bidirectional_rnn/bw/bw/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=[?,750], identical_element_shapes=true, tensor_array_name="bidirectional_rnn/bw/bw/dynamic_rnn/input_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_rnn/bw/bw/TensorArrayUnstack/strided_slice)]]
Error handling request
Traceback (most recent call last):
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 120, in handler_wrapper
    result = await result
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/deepspeech_server/driver/http_driver.py", line 30, in on_post_data
    "context": response_future
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/linq/observable/select.py", line 36, in on_next
    observer.on_next(result)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/linq/observable/merge.py", line 128, in on_next
    observer.on_next(x)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/subjects/subject.py", line 92, in on_next
    observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/deepspeech_server/driver/deepspeech_driver.py", line 81, in <lambda>
    sink.subscribe(lambda item: on_deepspeech_request(item))
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/deepspeech_server/driver/deepspeech_driver.py", line 67, in on_deepspeech_request
    text_observer.on_next({ "what": "text", "text": ds_model.stt(audio, fs), "context": item["context"]})
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/subjects/subject.py", line 92, in on_next
    observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/linq/observable/select.py", line 36, in on_next
    observer.on_next(result)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/subjects/subject.py", line 92, in on_next
    observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
    self.observer.on_next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/observerbase.py", line 19, in on_next
    self._on_next_core(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
    self._next(value)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/deepspeech_server/driver/console_driver.py", line 4, in <lambda>
    sink.subscribe( lambda i: print('console: ' + i))
TypeError: must be str, not NoneType
Unhandled exception
Traceback (most recent call last):
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 398, in start
    await resp.prepare(request)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/web_response.py", line 300, in prepare
    return await self._start(request)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/web_response.py", line 605, in _start
    return await super()._start(request)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/web_response.py", line 367, in _start
    await writer.write_headers(status_line, headers)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/http_writer.py", line 100, in write_headers
    self._write(buf)
  File "/home/jugs/anaconda3/envs/asr/lib/python3.6/site-packages/aiohttp/http_writer.py", line 57, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

**Comment by MainRo** [comment]
ok there are two things here:
- The model could not be loaded.
- The server is not robust to errors.

On the first point, is it possible that this instance uses a 0.2 pre-release of deepspeech (https://pypi.org/project/deepspeech/#history), with models of 0.1 ? Since the deepspeech dependency is neither in setup.py or requirements.txt, this is highly probable.

Concerning the second problem, the feature-cyclotron branch that I work on currently should improve the situation and send HTTP errors instead of crashing the server. I will merge it to master when it is ready.

**Comment by jageshmaharjan** [comment]
Thanks,  @MainRo , deepspeech "0.2.0a5" worked for me. earlier I had 0.1 and within it, parameters are at the different position.
[Closing]
