### ISSUE TITLE
Update for deepspeech 0.6.0

### ISSUE THREAD

**Issue by MainRo** [MainRo/deepspeech-server#25]
Models and APIs have changed in deepspeech 0.6.0. The server must be updated to use these new APIs.

**Comment by cypherphage** [comment]
I am getting this error. I have installed everything

deepspeech-server : command not found

**Comment by cypherphage** [comment]
I am using deepspeech 0.5.1

deepspeech-server --config config.json

Traceback (most recent call last):
  File "/home/cypherphage/venv/bin/deepspeech-server", line 5, in <module>
    main()
  File "/home/cypherphage/venv/lib/python3.6/site-packages/deepspeech_server/server.py", line 157, in main
    file=file.make_driver()
  File "/home/cypherphage/venv/lib/python3.6/site-packages/cyclotron_aio/runner.py", line 8, in run
    program = setup(entry_point, drivers)
  File "/home/cypherphage/venv/lib/python3.6/site-packages/cyclotron/rx.py", line 67, in setup
    sinks = entry_point.call(sources)
  File "/home/cypherphage/venv/lib/python3.6/site-packages/deepspeech_server/server.py", line 128, in deepspeech_server
    error_map=lambda e: httpd.Response(
TypeError: let_bind() got an unexpected keyword argument 'error_map'

**Comment by MainRo** [comment]
This error is not related to deepspeech 0.6.0, so please do not use this issue.
BTW you can fix this by upgrading rxpy to v1.6.1. cf #26

**Comment by krupalkp97** [comment]
Hey , 
what are the changes we need to do to update the server to be able to support deepspeech v0.6.0?

As i have updated deepspeech version 0.6.0 but still i got error for model incompatible.
`TypeError: CreateModel() takes at most 2 arguments (5 given)
` 

Thanks in advance
