### ISSUE TITLE
TypeError: let_bind() got an unexpected keyword argument 'error_map'

### ISSUE THREAD

**Issue by atd** [MainRo/deepspeech-server#26]
I just installed `deepspeec-server` using a fresh virtualenv in debian testing

I get this error:

```
$ deepspeech-server --config config.json
Traceback (most recent call last):
  File "/home/test/deepspeech/venv/bin/deepspeech-server", line 5, in <module>
    main()
  File "/home/test/deepspeech/venv/lib/python3.7/site-packages/deepspeech_server/server.py", line 157, in main
    file=file.make_driver()
  File "/home/test/deepspeech/venv/lib/python3.7/site-packages/cyclotron_aio/runner.py", line 8, in run
    program = setup(entry_point, drivers)
  File "/home/test/deepspeech/venv/lib/python3.7/site-packages/cyclotron/rx.py", line 67, in setup
    sinks = entry_point.call(sources)
  File "/home/test/deepspeech/venv/lib/python3.7/site-packages/deepspeech_server/server.py", line 128, in deepspeech_server
    error_map=lambda e: httpd.Response(
TypeError: let_bind() got an unexpected keyword argument 'error_map'
```

Package versions are from https://github.com/MainRo/deepspeech-server/issues/23#issuecomment-560631462

```
$ pip list
Package           Version
----------------- -------
aiohttp           3.6.2  
async-timeout     3.0.1  
attrs             19.3.0 
chardet           3.0.4  
cyclotron         0.6.1  
cyclotron-aio     0.7.0  
cyclotron-std     0.5.0  
deepspeech        0.5.1  
deepspeech-server 1.1.0  
idna              2.8    
multidict         4.6.1  
numpy             1.17.4 
pip               19.3.1 
pkg-resources     0.0.0  
Rx                1.6.0  
scipy             1.3.3  
setuptools        42.0.2 
wheel             0.33.6 
yarl              1.4.2  
```

**Comment by MainRo** [comment]
can you try upgrading rx to 1.6.1 ? not sure but this may be the cause of the error.

**Comment by atd** [comment]
That's it! Upgrading 1.6.1 solved the issue.

**Comment by kirill-dev-pro** [comment]
I have identical pip list and `rx==1.6.1` from `pip install -r requirements.txt` but still have this error
